### PR TITLE
Create `owners.json` for `lumin` scope

### PR DESCRIPTION
**Pull request by 2jammers**
This adds @2jammers  and @AridAjd.
https://github.com/lumin-dev

### CODE REVIEW

**Comment by Dekkonot** [comment]
In order to update the owners of an organization, I need you to be a public member of it. Just as a safety precaution.

**Comment by AridAjd** [comment]
> In order to update the owners of an organization, I need you to be a public member of it. Just as a safety precaution.

@2jammers and I are the owners of the organization.

image

**Comment by Dekkonot** [comment]
I believe you, but the organization has no public members so I can't actually verify the claim:
image

**Comment by 2jammers** [comment]
I've changed my status, you should be able to confirm it.

**Pull request merged**
