### PR TITLE
Updated package owners for GameAnalytics

### PR DESCRIPTION
**Pull request by dorin-ga**
Hello, we need to change the owners of the GameAnalytics package in order to continue updating the wally package. Thanks in advance.

### CODE REVIEW

**Comment by sasial-dev** [comment]
Just a heads up you'll need to have your org status public to verify that you're part of the org!

**Comment by dorin-ga** [comment]
Done @sasial-dev

**Comment by Dekkonot** [comment]
Hi @dorin-ga, sorry for the delay in getting back to you on this. Just to confirm, the users you're adding as an owner are yourself (ID: 88650886), [ga-services-account](https://github.com/ga-services-account) (ID: 9884170) and [nikolajpedersen](https://github.com/nikolajpedersen) (ID: 1226306), correct?

**Comment by dorin-ga** [comment]
Hi @Dekkonot, yes, that is correct.

**Pull request merged**
